<?php if($block->getData('header')): $hs = $block->getData('size') ?>
    <<?= $hs ?> class='posts'><?php echo $block->getData('header'); ?></<?= $hs ?>>
<?php endif; ?>
<?php $catId = $block->getData('category_id') ?: null; ?>
<?php if ($logos = $block->getLogos($catId)): ?>
<section>
    <ul class="my-list" data-slick='{"slidesToScroll": 1}'>
    <?php foreach ($logos as $logo): ?>
        <li><?= $logo->getTitle() ?></li>
    <?php endforeach; ?>
    </ul>
</section>
<script>
    require([
        'jquery',
        'slick',
        'domReady!'
    ], function ($) {
        $(".my-list").slick({
            dots: false,
            arrows: false,
            infinite: true,
            speed: 800,
            autoplay: true,
            autoplaySpeed: 4000,
            slidesToShow: 4,
            responsive: [{
                breakpoint: 1024,
                settings: {
                    slidesToShow: 3
                }
            }, {
                breakpoint: 600,
                settings: {
                    slidesToShow: 2
                }
            }]
        });
    });
</script>
<?php endif; ?>
